version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "5478:1194/udp"
    restart: unless-stopped
    volumes:
     - ${ROOT}:/etc/openvpn
