global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9147']

  - job_name: 'plex'
    static_configs:
      - targets: ['plex-exporter:9594']

remote_write:
  - url: 'url'
    basic_auth:
      username: 'user'
      password: 'passwd'
