version: '3.8'

services:

  docker-exporter:
    image: prometheusnet/docker_exporter
    container_name: docker-exporter
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9147
    ports:
      - "9147:9147"