version:  "2.1"
services:
  wetty:
    image: svenihoney/wetty:latest
    #networks: # you can comment the next two lines if you are not going to reverse proxy.
     # - pwh
    container_name: wetty
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - REMOTE_SSH_USER=${REMOTE_SSH_USER} # change to your ssh user
      - REMOTE_SSH_SERVER=${REMOTE_SSH_SERVER}
      - REMOTE_SSH_PORT=${REMOTE_SSH_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3002:3000
    restart: unless-stopped
